"""Write the standard 3DGS binary PLY that every splat viewer reads."""

from __future__ import annotations

import numpy as np

def properties_for(rest_count: int):
    """Property names in the order every 3DGS reader expects them."""
    return (
        ["x", "y", "z", "nx", "ny", "nz"]
        + [f"f_dc_{i}" for i in range(3)]
        + [f"f_rest_{i}" for i in range(rest_count * 3)]
        + ["opacity"]
        + [f"scale_{i}" for i in range(3)]
        + [f"rot_{i}" for i in range(4)]
    )


PROPERTIES = properties_for(0)


def write_ply(path, means, features_dc, features_rest, logit_opacity, log_scales, quats):
    """Values go out in the same activated form the reference implementation uses.

    Positions are raw, colours are SH coefficients, opacity is a logit, scales
    are logs and rotations are normalised quaternions (w,x,y,z) -- so a reader
    applies sigmoid/exp/normalise and gets the model back.

    The higher SH bands are stored channel-major -- every coefficient for red,
    then green, then blue -- because that is the layout the reference writes and
    therefore the one every viewer expects. Interleaving them instead produces a
    file that loads without complaint and renders with the colours smeared
    across the bands.
    """
    means = np.asarray(means, dtype=np.float32)
    n = means.shape[0]

    quats = np.asarray(quats, dtype=np.float32)
    quats = quats / np.maximum(np.linalg.norm(quats, axis=1, keepdims=True), 1e-8)

    dc = np.asarray(features_dc, dtype=np.float32).reshape(n, -1, 3)
    rest = np.asarray(features_rest, dtype=np.float32).reshape(n, -1, 3)
    rest_count = rest.shape[1]
    properties = properties_for(rest_count)

    columns = [
        means,
        np.zeros((n, 3), dtype=np.float32),                 # normals: unused by 3DGS
        # (n, 1, 3) -> (n, 3, 1) -> (n, 3): one value per channel.
        dc.transpose(0, 2, 1).reshape(n, 3),
    ]
    if rest_count:
        # (n, 15, 3) -> (n, 3, 15) -> (n, 45): all of red's bands, then green's.
        columns.append(rest.transpose(0, 2, 1).reshape(n, rest_count * 3))
    columns += [
        np.asarray(logit_opacity, dtype=np.float32).reshape(n, 1),
        np.asarray(log_scales, dtype=np.float32).reshape(n, 3),
        quats,
    ]
    data = np.concatenate(columns, axis=1).astype("<f4")
    assert data.shape[1] == len(properties), (data.shape, len(properties))

    header = "\n".join(
        ["ply", "format binary_little_endian 1.0", "comment generated by SplatWorks"]
        + [f"element vertex {n}"]
        + [f"property float {p}" for p in properties]
        + ["end_header", ""]
    ).encode("ascii")

    with open(path, "wb") as fh:
        fh.write(header)
        fh.write(data.tobytes(order="C"))
    return len(header) + data.nbytes
