"""Write the standard 3DGS binary PLY that every splat viewer reads."""

from __future__ import annotations

import numpy as np

PROPERTIES = (
    ["x", "y", "z", "nx", "ny", "nz"]
    + [f"f_dc_{i}" for i in range(3)]
    + ["opacity"]
    + [f"scale_{i}" for i in range(3)]
    + [f"rot_{i}" for i in range(4)]
)


def write_ply(path, means, features, logit_opacity, log_scales, quats):
    """Values go out in the same activated form the reference implementation uses.

    Positions are raw, colours are degree-0 SH coefficients, opacity is a logit,
    scales are logs and rotations are normalised quaternions (w,x,y,z) -- so a
    reader applies sigmoid/exp/normalise and gets the model back.
    """
    means = np.asarray(means, dtype=np.float32)
    n = means.shape[0]

    quats = np.asarray(quats, dtype=np.float32)
    quats = quats / np.maximum(np.linalg.norm(quats, axis=1, keepdims=True), 1e-8)

    columns = [
        means,
        np.zeros((n, 3), dtype=np.float32),                 # normals: unused by 3DGS
        np.asarray(features, dtype=np.float32).reshape(n, 3),
        np.asarray(logit_opacity, dtype=np.float32).reshape(n, 1),
        np.asarray(log_scales, dtype=np.float32).reshape(n, 3),
        quats,
    ]
    data = np.concatenate(columns, axis=1).astype("<f4")
    assert data.shape[1] == len(PROPERTIES), (data.shape, len(PROPERTIES))

    header = "\n".join(
        ["ply", "format binary_little_endian 1.0", "comment generated by SplatWorks"]
        + [f"element vertex {n}"]
        + [f"property float {p}" for p in PROPERTIES]
        + ["end_header", ""]
    ).encode("ascii")

    with open(path, "wb") as fh:
        fh.write(header)
        fh.write(data.tobytes(order="C"))
    return len(header) + data.nbytes
